### ISSUE TITLE
AttributeError: 'FileFinder' object has no attribute 'find_module'

### ISSUE THREAD

**Issue by johndamiani** [JustAnotherArchivist/snscrape#1041]
I am runnung python 3.12 and snscrape version ( 0.7.0.20230622).

I am getting the following error when I try to import the package.
import snscrape.modules.twitter as sntwitter

Error:
(ib_venv) johndamiani@Johns-MacBook-Air Portfolio_analyser_2 % /Users/johndamiani/Desktop/Portfolio_analyser_2/ib_venv/bin/python /Users/johndamiani/Desktop/Portfolio_analyser_2/testi
ng.py
Traceback (most recent call last):
  File "/Users/johndamiani/Desktop/Portfolio_analyser_2/testing.py", line 4, in <module>
    import snscrape.modules.twitter as sntwitter
  File "/Users/johndamiani/Desktop/Portfolio_analyser_2/ib_venv/lib/python3.12/site-packages/snscrape/modules/__init__.py", line 17, in <module>
    _import_modules()
  File "/Users/johndamiani/Desktop/Portfolio_analyser_2/ib_venv/lib/python3.12/site-packages/snscrape/modules/__init__.py", line 13, in _import_modules
    module = importer.find_module(moduleName).load_module(moduleName)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'

Has anyone encountered this issue or has any ideas what might be causing this?

**Comment by TheTechRobo** [comment]
#782 ?

**Comment by AIConstructor** [comment]
Maybe the code block which is revised acc. new version of python fixes : 

[Original code](https://github.com/JustAnotherArchivist/snscrape/blob/614d4c2029a62d348ca56598f87c425966aaec66/snscrape/modules/__init__.py#L13)

`import importlib

__all__ = []

def _import_modules():
    prefixLen = len(__name__) + 1
    for finder, name, ispkg in importlib.util.find_spec(__path__[0]).submodule_search_locations:
        if not ispkg:
            module_name = name[prefixLen:]
            __all__.append(module_name)
            module = importlib.import_module(name)
            globals()[module_name] = module

_import_modules()
`

**Comment by AugastineNdeti** [comment]
yes, i have tried to run this code and getting the same:

import snscrape.modules.twitter as sntwitter
import pandas as pd

query= "python"
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    print(vars(tweet))
    break

**Comment by Ashique-1010** [comment]
snscrape does not seem to be supported in  python version > 3.11
The module will work in python 3.10, 3.9. I've tried it in google colab and it works.

**Comment by AbdelMoncif** [comment]
ive tried it on version 3.9.13 sale error

**Comment by TeemuSo** [comment]
Yeah, doesn't work on any python version form me.

**Comment by 3l1k** [comment]
find_module and load_module are deprecated api's that were removed in Python 3.12.
fix this by using importlib.import_module instead.
