### ISSUE TITLE
snscrape not working with Python under 3.8

### ISSUE THREAD

**Issue by tobe93gf** [JustAnotherArchivist/snscrape#424]
Hi JustAnotherArchivist, the latest version of snscrape has a lot of features but does not work with Python under 3.8. so I decided to change it to be useable with Python under 3.8. [changed snscrape](https://github.com/tobe93gf/snscrape). Also I've fixed some errors. Tnx for your amazing code. I like to know your opinion.

**Comment by JustAnotherArchivist** [comment]
> the latest version of snscrape has a lot of features but does not work with Python under 3.8.

Yes, see #181. snscrape is open-source, so naturally you're free to maintain your fork for old Python versions. I won't be merging that back though. Over time, the code relying on 3.8+ will increase as well.

> Also I've fixed some errors.

If these are errors that also affect my code (not just Python 3.7 compatibility) and haven't been reported before, please file issues for them. Since you created an empty repository from the snscrape files rather than forking, I can't easily figure out your changes. (I'm not interested in walking through a giant diff.)

**Comment by tobe93gf** [comment]
I am new to Python and Github, and I dont know how forking work.
one of the errors that made code crash was [423](https://github.com/JustAnotherArchivist/snscrape/issues/423) and I fixed it somehow.
### Errors were:
missing 1 required positional argument: 'title' , and missing 1 required positional argument: 'url'

**Comment by TheTechRobo** [comment]
Oh, JustAnotherArchivist is working on fixing those in a much better way than just setting the fields to optional.

Forking works by pressing the fork button in the top right, for what it's worth.

**Comment by JustAnotherArchivist** [comment]
Yeah, that's #407 and still work in progress. I've been distracted a bit by recent events in the world, so not much progress has been made lately, but it will eventually be fixed properly. Until then, I recommend using either the release version or (in particular if you need the `twitter-profile` scraper) the commit prior to when I introduced cards.

**Comment by tobe93gf** [comment]
> Oh, JustAnotherArchivist is working on fixing those in a much better way than just setting the fields to optional.
> 
> Forking works by pressing the fork button in the top right, FWIW.

I said I'm new to Python. And JustAnotherArchivist himself set the 'thumbnailUrl' and 'description' to optional. Why those were not wrong?
